spring.application.name=demo
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.name="Spring Learning Demo"
info.app.description="My App description"
info.app.version=1.0
spring.security.user.name=kapil
spring.security.user.password=demo123