spring.application.name=crudwithdb
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=root
spring.datasource.password=Demo@1234
#
# Spring Data REST settings
#
spring.data.rest.base-path=/magic-api